image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview
checkoutLocation: "go/src/github.com/demo-apps/go-gin-app"
workspaceLocation: "go/src/github.com/demo-apps/go-gin-app"
tasks:
  - init: >
      go get -v ./... && go build -o app
    command: >
      ./app
github:
  prebuilds:
    pullRequestsFromForks: true
